apiVersion: v1
kind: Service
metadata:
  namespace: ssh-debian
  name: ssh-debian-app-service
spec:
  type: NodePort
  selector:
    app: ssh-debian-app
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 22
      nodePort: 30022